"use client";
import {useState} from "react";
import Link from "next/link";
import {allocatePlan,calendarStatus,DEFAULT_MIX,operationsMetrics,recurringSlots,weekBounds,type Category,type ContentPlan,type OperationsData,type PlanItem,type RecurringSchedule} from "@/lib/content-operations";
import {kstInput,kstInputToIso} from "@/lib/draft-scheduling";
import {BUILTIN_TEMPLATES,AI_PURPOSES} from "@/lib/ai-content";
import type {DraftRow} from "@/lib/supabase/database.types";
type Props={view:string;base:string;data:OperationsData;drafts:DraftRow[];now:string;accountId:string;accountLabel:string;onChange:(data:OperationsData)=>void;onDrafts:(rows:DraftRow[])=>void;initialFill?:boolean};
const weekdays=["일","월","화","수","목","금","토"];
function CategoryTag({category}:{category?:Category}){return <span className="ops-category" style={{"--category-color":category?.color??"#88929f"} as React.CSSProperties}>{category?.name??"미분류"}</span>;}
const Bar=({title,rows}:{title:string;rows:{label:string;value:number}[]})=><section className="pro-card"><h2>{title}</h2><div className="ops-bars">{rows.map(row=><div key={row.label}><span>{row.label}</span><div><i style={{width:(row.value/Math.max(1,...rows.map(r=>r.value))*100)+"%"}}/></div><b>{row.value}</b></div>)}</div>{!rows.length&&<p className="pro-help">이 기간의 실제 게시 데이터가 아직 없습니다.</p>}</section>;
export function OperationsPanel({view,base,data,drafts,now,accountId,accountLabel,onChange,onDrafts,initialFill=false}:Props){
 const week=weekBounds(now),today=kstInput(now).slice(0,10),existing=data.plans.find(p=>p.start_date<=week.end&&p.end_date>=week.start),[start,setStart]=useState(week.start),[end,setEnd]=useState(week.end);
 const [business,setBusiness]=useState(existing?.business??""),[goal,setGoal]=useState(existing?.goal??""),[audience,setAudience]=useState(existing?.audience??""),[count,setCount]=useState(existing?.target_count??14);
 const [mix,setMix]=useState<Record<string,number>>(existing?.mix??DEFAULT_MIX),[plan,setPlan]=useState<ContentPlan|null>(null),[dirty,setDirty]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[reviewed,setReviewed]=useState(false);
 const [perDay,setPerDay]=useState(Math.ceil(14/Math.max(1,(Date.parse(week.end)-Date.parse(today))/86400000+1))),[firstTime,setFirstTime]=useState("10:00"),[lastTime,setLastTime]=useState("20:00");
 const [categoryFilter,setCategoryFilter]=useState(""),[statusFilter,setStatusFilter]=useState(""),[calendarMode,setCalendarMode]=useState<"month"|"week">("month"),[focus,setFocus]=useState(today);
 const [recurrence,setRecurrence]=useState<RecurringSchedule|null>(null),[repeatName,setRepeatName]=useState(""),[repeatDays,setRepeatDays]=useState([1,3,5]),[repeatTime,setRepeatTime]=useState("10:00"),[repeatCategory,setRepeatCategory]=useState(""),[repeatTemplate,setRepeatTemplate]=useState(""),[repeatPurpose,setRepeatPurpose]=useState("정보 전달"),[repeatStart,setRepeatStart]=useState(today),[repeatEnd,setRepeatEnd]=useState("");
 const [categoryEdit,setCategoryEdit]=useState<Category|null>(null),[categoryName,setCategoryName]=useState(""),[categoryColor,setCategoryColor]=useState("#5085cb");
 const activeCategories=data.categories.filter(c=>!c.archived_at),metrics=operationsMetrics(drafts,data,view==="dashboard"?week.start:start,view==="dashboard"?week.end:end);
 const effectiveMix=Object.fromEntries(activeCategories.map(c=>[c.name,mix[c.name]??0]));
 const category=(id:string|null)=>data.categories.find(c=>c.id===id);
 async function request(payload?:unknown,path=base+"/operations"){
 const response=await fetch(path,{method:payload?"POST":"GET",cache:"no-store",credentials:"same-origin",...(payload?{headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}:{}),signal:AbortSignal.timeout(175000)});
 const result=await response.json();if(!response.ok)throw new Error(result.error??"저장하지 못했습니다.");return result;
 }
 async function run(callback:()=>Promise<void>){if(busy)return;setBusy(true);setError("");setNotice("");try{await callback();}catch(e){setError(e instanceof Error?e.message:"처리하지 못했습니다.");}finally{setBusy(false);}}
 async function reload(){const result=await request();onChange(result);return result as OperationsData;}
 const updateItem=(id:string,changes:Partial<PlanItem>)=>{setPlan(p=>p?{...p,items:p.items.map(i=>i.id===id?{...i,...changes}:i)}:null);setDirty(true);setReviewed(false);};
 async function persist(current=plan){if(!current)throw new Error("계획을 선택하세요.");if(!dirty)return current;
 const result=await request({action:"savePlan",planId:current.id,expectedUpdatedAt:current.updated_at,items:current.items});setPlan(result.plan);setDirty(false);await reload();return result.plan as ContentPlan;}
 async function create(fill=false){await run(async()=>{const result=await request({action:fill?"fill":"createPlan",requestId:crypto.randomUUID(),business,goal,audience,count,startDate:start,endDate:end,mix:effectiveMix});
 if(result.complete){setNotice(result.message);return;}setPlan(result.plan);setPerDay(Math.ceil(result.plan.items.length/Math.max(1,(Date.parse(end)-Math.max(Date.parse(start),Date.parse(today)))/86400000+1)));setDirty(false);setReviewed(false);await reload();setNotice(fill?"부족한 콘텐츠 계획을 만들었습니다. 글 생성 후 검토해 배치하세요.":"주간 계획을 저장했습니다. 주제를 편집한 뒤 전체 글 생성을 누르세요.");});}
 async function generate(){await run(async()=>{const current=await persist();const result=await request({action:"generatePosts",planId:current.id,expectedUpdatedAt:current.updated_at,requestId:crypto.randomUUID()});setPlan(result.plan);setReviewed(false);await reload();setNotice("실제 AI 글을 생성해 저장했습니다. 글과 시간을 검토하세요.");});}
 function allocate(){if(!plan)return;try{const rows=allocatePlan(plan.items,plan.start_date,plan.end_date,perDay,firstTime,lastTime,drafts.filter(d=>d.scheduled_at&&d.publication_status!=="failed").map(d=>d.scheduled_at!),data.recurrences);
 setPlan({...plan,items:rows});setDirty(true);setReviewed(false);setError("");setNotice("기존 예약을 피해 시간을 배분했습니다. 반복 슬롯을 먼저 사용합니다.");}catch(e){setError(e instanceof Error?e.message:"시간을 확인해 주세요.");}}
 async function place(){await run(async()=>{const current=await persist();const result=await request({action:"place",planId:current.id,expectedUpdatedAt:current.updated_at,accountId:accountId||null,reviewed});
 onDrafts(result.drafts);const updated=await reload();setPlan(updated.plans.find(p=>p.id===current.id)??null);setNotice(result.drafts.length+"개를 Calendar와 Queue에 배치했습니다.");setDirty(false);});}
 const quick=<div className="ops-quick">{[["AI 글 만들기","/composer?tab=ai"],["10개 만들기","/composer?tab=multiple"],["이번 주 계획","/planner"],["빈 슬롯 채우기","/planner?fill=1"],["예약글 보기","/queue"],["캘린더 보기","/calendar"]].map(([label,href])=><Link key={href} href={href}>{label} <span>↗</span></Link>)}</div>;
 if(view==="dashboard"){
 const ready=drafts.filter(d=>d.scheduled_at&&kstInput(d.scheduled_at).slice(0,10)>=week.start&&kstInput(d.scheduled_at).slice(0,10)<=week.end&&d.publication_status!=="failed");
 return <div className="ops-dashboard">{quick}<section className="pro-card ops-week"><div><span className="pro-eyebrow">THIS WEEK</span><h2>이번 주 콘텐츠 준비</h2><p>{metrics.target?metrics.target+"개 목표 중 "+metrics.prepared+"개가 준비되었습니다.":"이번 주 계획을 세우고 꾸준한 운영을 시작하세요."}</p></div>
 <div className="ops-week-numbers"><span>주간 목표<b>{metrics.target}</b></span><span>예약 완료<b>{metrics.scheduled}</b></span><span>게시 완료<b>{metrics.published}</b></span><span>부족 콘텐츠<b>{metrics.missing}</b></span></div>
 <progress max={metrics.target||1} value={Math.min(metrics.target,metrics.prepared)} aria-label="이번 주 준비율"/><Link className="pro-button primary" href={metrics.missing?"/planner?fill=1":"/planner"}>{metrics.missing?metrics.missing+"개 AI 생성":"이번 주 계획"}</Link></section>
 <section className="pro-card"><div className="pro-card-title"><h2>이번 주 콘텐츠 구성</h2><Link href="/analytics">운영 분석 ↗</Link></div><div className="ops-mix-bars">{activeCategories.map(c=>{const n=ready.filter(d=>d.category_id===c.id).length;return n?<div key={c.id}><CategoryTag category={c}/><progress max={ready.length||1} value={n}/><b>{Math.round(n/(ready.length||1)*100)}%</b></div>:null;})}</div>{!ready.length&&<p className="pro-help">예약한 글의 카테고리 비율이 표시됩니다.</p>}</section></div>;
 }
 const feedback=<>{error&&<div role="alert" className="pro-feedback error">{error}</div>}{notice&&<div role="status" className="pro-feedback success">{notice}</div>}{busy&&<div role="status" className="pro-feedback">저장 또는 AI 생성 중… 완료 후 결과가 표시됩니다.</div>}</>;
 const dateFields=<div className="ops-fields"><label>시작 날짜<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>종료 날짜<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>;
 if(view==="planner")return <div className="ops-planner">{feedback}<div className="ops-planner-layout"><section className="pro-card ops-form"><span className="pro-eyebrow">PLAN → CREATE → SCHEDULE</span><h2>{initialFill?"빈 슬롯을 새 콘텐츠로 채우세요.":"이번 주, 어떤 이야기를 할까요?"}</h2>
 <label>사업 / 계정<input value={business} maxLength={180} placeholder="BlueGEE Audio" onChange={e=>setBusiness(e.target.value)}/></label>
 <label>이번 주 목표<textarea rows={2} value={goal} maxLength={500} placeholder="VST 제품 인지도 높이기" onChange={e=>setGoal(e.target.value)}/></label>
 <label>대상 독자<input value={audience} maxLength={200} placeholder="홈레코딩 사용자" onChange={e=>setAudience(e.target.value)}/></label>
 <label>목표 게시 수<input type="number" min={1} max={30} value={count} onChange={e=>setCount(Number(e.target.value))}/></label>{dateFields}
 <details className="ops-details" open><summary>콘텐츠 믹스 <b>{Object.values(effectiveMix).reduce((a,b)=>a+b,0)}%</b></summary><div className="ops-mix-inputs">{activeCategories.map(c=><label key={c.id}>{c.name}<input type="number" min={0} max={100} value={mix[c.name]??0} onChange={e=>setMix({...mix,[c.name]:Number(e.target.value)})}/><span>%</span></label>)}</div>
 <button className="pro-button ghost" onClick={()=>{const total=Object.values(effectiveMix).reduce((a,b)=>a+b,0);if(!total)return;const entries=Object.entries(effectiveMix).map(([k,v])=>[k,Math.floor(v/total*100)] as const);let rest=100-entries.reduce((s,[,v])=>s+v,0);setMix(Object.fromEntries(entries.map(([k,v])=>[k,v+(rest-->0?1:0)])));}}>100%로 맞추기</button></details>
 <div className="pro-row-actions"><button className="pro-button primary" disabled={busy||!business.trim()||!goal.trim()||Object.values(effectiveMix).reduce((a,b)=>a+b,0)!==100} onClick={()=>create(false)}>주간 계획 생성</button><button className="pro-button ghost" disabled={busy||!business.trim()||!goal.trim()||Object.values(effectiveMix).reduce((a,b)=>a+b,0)!==100} onClick={()=>create(true)}>빈 슬롯 채우기</button></div>
 <p className="pro-help">AI 생성에는 API 사용량이 발생합니다. 부족한 수를 계산하고 기존 내용과 겹치지 않는 주제를 제안합니다. 검토 후에만 큐에 들어갑니다.</p>
 <div className="ops-plan-list"><h3>저장된 계획</h3>{data.plans.map(p=><button key={p.id} disabled={busy} onClick={()=>{setPlan(p);setBusiness(p.business);setGoal(p.goal);setAudience(p.audience);setStart(p.start_date);setEnd(p.end_date);setCount(p.target_count);setMix(p.mix);setPerDay(Math.ceil(p.items.length/Math.max(1,(Date.parse(p.end_date)-Math.max(Date.parse(p.start_date),Date.parse(today)))/86400000+1)));setDirty(false);setReviewed(false);}}><strong>{p.business}</strong><small>{p.start_date} · {p.items.length}개 · {p.status==="scheduled"?"배치 완료":p.status==="ready"?"글 준비":"계획"}</small></button>)}</div></section>
 <div>{!plan?<section className="pro-card pro-empty"><h2>목표를 실제 콘텐츠로 바꿔보세요.</h2><p>계획 생성 → 주제 편집 → 전체 글 생성 → 시간 배분 → 검토 후 배치</p></section>:<>
 <section className="pro-card"><div className="pro-card-title"><h2>{plan.business} · {plan.items.length}개 계획</h2><span>{dirty?"저장할 변경 있음":plan.status==="scheduled"?"배치 완료":"DB 저장됨"}</span></div><p>{plan.goal}</p><p className="pro-help">{plan.start_date} ~ {plan.end_date} · 콘텐츠 믹스에 따라 카테고리별 글 수를 배분했습니다.</p>
 {plan.status!=="scheduled"&&<><div className="ops-fields"><label>하루 게시 수<input type="number" min={1} max={30} value={perDay} onChange={e=>setPerDay(Number(e.target.value))}/></label><label>시작 시간<input type="time" value={firstTime} onChange={e=>setFirstTime(e.target.value)}/></label><label>종료 시간<input type="time" value={lastTime} onChange={e=>setLastTime(e.target.value)}/></label></div>
 <div className="pro-row-actions"><button className="pro-button ghost" disabled={busy||!dirty} onClick={()=>run(async()=>{await persist();setNotice("계획 변경을 저장했습니다.");})}>계획 저장</button><button className="pro-button primary" disabled={busy||plan.items.every(i=>i.aiPostId)} onClick={generate}>전체 글 생성</button><button className="pro-button ghost" disabled={busy} onClick={allocate}>이번 주 자동 시간 배분</button></div></>}
 </section><div className="ops-plan-items">{plan.items.map((item,index)=><section className="pro-card" key={item.id}><div className="pro-card-title"><h3>{index+1}. {item.day}</h3><CategoryTag category={category(item.categoryId)}/></div>
 <label>콘텐츠 주제<input value={item.topic} maxLength={180} disabled={busy||plan.status==="scheduled"} onChange={e=>updateItem(item.id,{topic:e.target.value})}/></label>
 <label>카테고리<select value={item.categoryId??""} disabled={busy||plan.status==="scheduled"} onChange={e=>updateItem(item.id,{categoryId:e.target.value||null})}>{activeCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 {item.aiPostId&&<><label>게시물 본문<textarea rows={6} value={item.body} disabled={busy||plan.status==="scheduled"} onChange={e=>updateItem(item.id,{body:e.target.value})}/></label><div className="pro-character-count"><span>{item.purpose}</span><span>{Array.from(item.body).length} / 500</span></div></>}
 <label>게시 일시 (KST)<input type="datetime-local" disabled={busy||plan.status==="scheduled"} value={item.scheduledAt?kstInput(item.scheduledAt):item.day+"T10:00"} onChange={e=>{try{updateItem(item.id,{scheduledAt:kstInputToIso(e.target.value),day:e.target.value.slice(0,10)});}catch{setError("날짜를 확인해 주세요.");}}}/></label>
 {item.draftId&&<Link href={"/composer?draft="+item.draftId}>예약한 글 편집 ↗</Link>}</section>)}</div>
 {plan.status!=="scheduled"?<section className="pro-card ops-placement"><label className="pro-check-label"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>모든 글과 예약 시간을 검토했습니다.</label><button className="pro-button primary" disabled={busy||!reviewed||!plan.items.every(i=>i.aiPostId&&i.body.trim()&&Array.from(i.body).length<=500&&i.scheduledAt)} onClick={place}>Calendar + Queue 전체 배치</button></section>:<section className="pro-card"><Link className="pro-button primary" href="/calendar">Calendar 확인</Link> <Link className="pro-button ghost" href="/queue">Queue 확인</Link></section>}
 </>}</div></div></div>;
 if(view==="calendar"){
 const date=new Date(focus+"T00:00:00Z"),first=calendarMode==="week"?weekBounds(focus+"T12:00:00+09:00").start:new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),1)).toISOString().slice(0,10);
 const origin=new Date(first+"T00:00:00Z");if(calendarMode==="month")origin.setUTCDate(origin.getUTCDate()-origin.getUTCDay());
 const days=Array.from({length:calendarMode==="week"?7:42},(_,i)=>new Date(origin.getTime()+i*86400000).toISOString().slice(0,10));
 const slots=recurringSlots(data.recurrences,days[0],days.at(-1)!);
 async function move(id:string,day:string){const draft=drafts.find(d=>d.id===id);if(!draft||draft.publication_status==="published"||draft.publication_status==="publishing"||!draft.publish_retryable)return;
 await run(async()=>{const scheduledAt=kstInputToIso(day+"T"+(draft.scheduled_at?kstInput(draft.scheduled_at).slice(11):"10:00"));const result=await request({body:draft.body,mode:"schedule",draftId:draft.id,expectedUpdatedAt:draft.updated_at,scheduledAt,accountId:draft.selected_threads_account_id,...(category(draft.category_id)?.archived_at?{}:{categoryId:draft.category_id})},base+"/posts");onDrafts([result.draft]);setNotice("예약 날짜를 변경했습니다.");});}
 return <>{feedback}<section className="pro-card ops-calendar-toolbar"><div className="pro-tabs">{(["month","week"] as const).map(mode=><button key={mode} className={mode===calendarMode?"selected":""} onClick={()=>setCalendarMode(mode)}>{mode==="month"?"월간":"주간"}</button>)}</div>
 <button aria-label="이전 기간" onClick={()=>{if(calendarMode==="week")date.setUTCDate(date.getUTCDate()-7);else{date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()-1);}setFocus(date.toISOString().slice(0,10));}}>←</button><input aria-label="캘린더 기준 날짜" type="date" value={focus} onChange={e=>setFocus(e.target.value)}/><button aria-label="다음 기간" onClick={()=>{if(calendarMode==="week")date.setUTCDate(date.getUTCDate()+7);else{date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()+1);}setFocus(date.toISOString().slice(0,10));}}>→</button>
 <select aria-label="카테고리 필터" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">전체 카테고리</option>{activeCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>
 <select aria-label="상태 필터" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">전체 상태</option>{["Draft","Scheduled","Queued","Published","Failed"].map(s=><option key={s}>{s}</option>)}</select>
 <Link className="pro-button ghost" href="/planner?fill=1">빈 슬롯 채우기</Link></section>
 <p className="pro-help">글을 클릭하면 상세 편집으로 이동합니다. 게시 전 카드는 미래 날짜로 드래그해 예약을 바꿀 수 있습니다. 점선 카드는 반복 슬롯으로, 콘텐츠 배치가 필요합니다.</p>
 <div className={"ops-calendar "+calendarMode}><div className="ops-calendar-weekdays">{(calendarMode==="week"?["월","화","수","목","금","토","일"]:weekdays).map(d=><b key={d}>{d}</b>)}</div><div className="ops-calendar-grid">{days.map(day=><div key={day} className={"ops-calendar-day "+(day===today?"today":"")} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void move(e.dataTransfer.getData("text/plain"),day);}}><time>{day.slice(5)}</time>
 {drafts.filter(d=>kstInput(d.scheduled_at??d.published_at??d.created_at).slice(0,10)===day&&(!categoryFilter||d.category_id===categoryFilter)&&(!statusFilter||calendarStatus(d)===statusFilter)).map(d=><Link href={"/composer?draft="+d.id} key={d.id} className={"ops-calendar-card "+calendarStatus(d).toLowerCase()} draggable={!busy&&d.publication_status==="unpublished"&&d.publish_retryable} onDragStart={e=>e.dataTransfer.setData("text/plain",d.id)}>
 <div><time>{kstInput(d.scheduled_at??d.published_at??d.created_at).slice(11)}</time><small>{calendarStatus(d)}</small></div><strong>{d.body.slice(0,70)||d.topic}</strong><CategoryTag category={category(d.category_id)}/><span>{accountLabel}</span></Link>)}
 {!statusFilter&&slots.filter(s=>kstInput(s.at).slice(0,10)===day&&(!categoryFilter||s.schedule.category_id===categoryFilter)&&!drafts.some(d=>d.scheduled_at&&Date.parse(d.scheduled_at)===Date.parse(s.at))).map(s=><Link href="/planner?fill=1" className="ops-calendar-slot" key={s.schedule.id+s.at}>{s.schedule.time_of_day.slice(0,5)} · {s.schedule.name}<small>반복 슬롯 · 콘텐츠 필요</small></Link>)}</div>)}</div></div></>;
 }
 if(view==="recurring")return <>{feedback}<div className="ops-planner-layout"><section className="pro-card ops-form"><h2>{recurrence?"반복 슬롯 편집":"반복 슬롯 만들기"}</h2><label>슬롯 이름<input value={repeatName} maxLength={100} placeholder="월요일 AI 뉴스 / 팁" onChange={e=>setRepeatName(e.target.value)}/></label>
 <label>반복 유형<select onChange={e=>setRepeatDays(e.target.value==="daily"?[0,1,2,3,4,5,6]:e.target.value==="weekdays"?[1,2,3,4,5]:e.target.value==="weekend"?[0,6]:repeatDays)} defaultValue="custom"><option value="custom">매주 / 사용자 지정 요일</option><option value="daily">매일</option><option value="weekdays">평일</option><option value="weekend">주말</option></select></label>
 <div className="ops-weekday-picks">{weekdays.map((d,i)=><label key={d}><input type="checkbox" checked={repeatDays.includes(i)} onChange={e=>setRepeatDays(e.target.checked?[...repeatDays,i]:repeatDays.filter(n=>n!==i))}/>{d}</label>)}</div>
 <label>한국 시간<input type="time" value={repeatTime} onChange={e=>setRepeatTime(e.target.value)}/></label><label>카테고리<select value={repeatCategory} onChange={e=>setRepeatCategory(e.target.value)}><option value="">미분류</option>{activeCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <label>콘텐츠 유형<select value={repeatPurpose} onChange={e=>setRepeatPurpose(e.target.value)}>{AI_PURPOSES.map(p=><option key={p}>{p}</option>)}</select></label>
 <label>연결 템플릿<select value={repeatTemplate} onChange={e=>setRepeatTemplate(e.target.value)}><option value="">콘텐츠 유형 사용</option>{[...BUILTIN_TEMPLATES,...(data.templates??[])].map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
 <div className="ops-fields"><label>시작<input type="date" value={repeatStart} onChange={e=>setRepeatStart(e.target.value)}/></label><label>종료 (선택)<input type="date" value={repeatEnd} onChange={e=>setRepeatEnd(e.target.value)}/></label></div>
 <button className="pro-button primary" disabled={busy||!repeatName||!repeatDays.length} onClick={()=>run(async()=>{await request({action:"recurrence",...(recurrence?{id:recurrence.id,expectedUpdatedAt:recurrence.updated_at}:{}),name:repeatName,days:repeatDays,time:repeatTime,categoryId:repeatCategory||null,templateId:repeatTemplate,contentType:repeatPurpose,startDate:repeatStart,endDate:repeatEnd||null});await reload();setRecurrence(null);setRepeatName("");setNotice("반복 슬롯을 저장했습니다. Planner의 자동 배치에 반영됩니다.");})}>반복 슬롯 저장</button><p className="pro-help">반복 규칙과 생성된 글은 별도로 관리합니다. 슬롯에 맞춘 콘텐츠를 검토해 배치하면 기존 자동 게시 큐가 실행합니다. 같은 글을 무검토로 반복 게시하지 않습니다.</p></section>
 <div>{data.recurrences.map(s=><section className="pro-card" key={s.id}><div className="pro-card-title"><h2>{s.name}</h2><span className={"pro-badge "+(s.enabled?"success":"neutral")}>{s.enabled?"운영 중":"일시 중지"}</span></div><p>{s.days.map(d=>weekdays[d]).join(" · ")}요일 {s.time_of_day.slice(0,5)} KST</p><CategoryTag category={category(s.category_id)}/><p className="pro-help">{s.content_type} · {[...BUILTIN_TEMPLATES,...(data.templates??[])].find(t=>t.id===s.template_id)?.name??"자유 템플릿"} · {s.start_date} ~ {s.end_date??"계속"}</p>
 <div className="pro-row-actions"><button onClick={()=>{setRecurrence(s);setRepeatName(s.name);setRepeatDays(s.days);setRepeatTime(s.time_of_day.slice(0,5));setRepeatCategory(s.category_id??"");setRepeatTemplate(s.template_id);setRepeatPurpose(s.content_type);setRepeatStart(s.start_date);setRepeatEnd(s.end_date??"");}}>수정</button><button disabled={busy} onClick={()=>run(async()=>{await request({action:"recurrence",id:s.id,expectedUpdatedAt:s.updated_at,enabled:!s.enabled});await reload();})}>{s.enabled?"중지 / 삭제":"다시 운영"}</button></div></section>)}
 {!data.recurrences.length&&<section className="pro-card pro-empty"><h2>꾸준한 콘텐츠 리듬을 만드세요.</h2><p>매일, 평일, 주말 또는 원하는 요일의 슬롯을 저장하세요.</p></section>}<Link href="/calendar">Calendar에서 반복 슬롯 보기 ↗</Link></div></div></>;
 if(view==="categories")return <>{feedback}<section className="pro-card ops-form"><h2>{categoryEdit?"카테고리 수정":"카테고리 추가"}</h2><div className="ops-fields"><label>이름<input value={categoryName} maxLength={40} onChange={e=>setCategoryName(e.target.value)}/></label><label>색상<input type="color" value={categoryColor} onChange={e=>setCategoryColor(e.target.value)}/></label></div>
 <button className="pro-button primary" disabled={busy||!categoryName.trim()} onClick={()=>run(async()=>{await request({action:"category",...(categoryEdit?{id:categoryEdit.id,expectedUpdatedAt:categoryEdit.updated_at}:{}),name:categoryName,color:categoryColor});await reload();setCategoryEdit(null);setCategoryName("");setNotice("카테고리를 저장했습니다.");})}>저장</button></section>
 <section className="pro-card">{activeCategories.map(c=><div className="ops-category-row" key={c.id}><CategoryTag category={c}/><span>{drafts.filter(d=>d.category_id===c.id).length}개 글</span><button onClick={()=>{setCategoryEdit(c);setCategoryName(c.name);setCategoryColor(c.color);}}>수정</button><button disabled={busy} onClick={()=>run(async()=>{await request({action:"category",id:c.id,expectedUpdatedAt:c.updated_at,archive:true});await reload();setNotice("카테고리를 숨겼습니다. 기존 글의 분류 기록은 보존됩니다.");})}>삭제</button></div>)}</section></>;
 if(view==="analytics"){
 return <>{feedback}<section className="pro-card">{dateFields}<p className="pro-help">실제 DB 기록으로 집계합니다. 게시 수·카테고리·시간대·계정은 성공한 게시 기준입니다. 예약 실행률은 기한이 도래한 예약 중 성공 비율입니다.</p></section>
 <div className="pro-stats">{[["성공 게시",metrics.published],["실패 게시",metrics.failed],["게시 예정",metrics.scheduled],["예약 실행률",metrics.executionRate===null?"—":metrics.executionRate+"%"]].map(([label,value])=><article className="pro-stat" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
 <div className="ops-chart-grid"><Bar title="날짜별 게시" rows={metrics.days.sort((a,b)=>a.label.localeCompare(b.label))}/><Bar title="카테고리별 게시" rows={metrics.categories}/><Bar title="시간대별 게시 (KST)" rows={metrics.hours.sort((a,b)=>a.label.localeCompare(b.label))}/><Bar title="AI / 직접 작성" rows={[{label:"AI 생성",value:metrics.ai},{label:"직접 작성",value:metrics.manual}]}/><Bar title="계정별 게시" rows={metrics.accounts.map(r=>({...r,label:data.accounts?.find(a=>a.id===r.label)?.username?"@"+data.accounts.find(a=>a.id===r.label)!.username:r.label==="기본 계정"?accountLabel:r.label}))}/></div>
 <section className="pro-card"><span className="pro-eyebrow">THREADS INSIGHTS</span><h2>반응과 성장</h2><div className="ops-insights">{["조회수","좋아요","답글","재게시","인용","참여율","팔로워 변화"].map(label=><div key={label}><strong>{label}</strong><span>Threads Insights 연결 후 제공</span></div>)}</div></section></>;
 }
 return null;
}

