"use client";
import {useState} from "react";
import Link from "next/link";
import {engagementScore,latestInsights,metricTotal,rankedPosts,winningPatterns,POST_METRICS,type PerformanceData} from "@/lib/threads-performance";
import {kstInput} from "@/lib/draft-scheduling";
import type {Category} from "@/lib/content-operations";
import type {DraftRow} from "@/lib/supabase/database.types";
import type {ThreadsConnection} from "@/lib/threads-publishing";
const value=(number:number|null|undefined)=>number===null||number===undefined?"Unavailable":new Intl.NumberFormat("ko-KR",{maximumFractionDigits:1}).format(number);
const date=(raw:string|null|undefined)=>raw?new Date(raw).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"}):"아직 없음";
const metricLabels={views:"Views",likes:"Likes",replies:"Replies",reposts:"Reposts",quotes:"Quotes",shares:"Shares"};
type Props={view:"dashboard"|"analytics";base:string;data:PerformanceData;drafts:DraftRow[];categories:Category[];connection:ThreadsConnection;now:string;onChange:(data:PerformanceData)=>void};
export function ThreadsPerformance({view,base,data,drafts,categories,connection,now,onChange}:Props){
 const [period,setPeriod]=useState<"24h"|"7d"|"30d"|"all">("7d"),[sort,setSort]=useState<"engagement"|"replies"|"reposts"|"views">("engagement"),[category,setCategory]=useState(""),[accountFilter,setAccountFilter]=useState("");
 const [selected,setSelected]=useState<string|null>(null),[followCount,setFollowCount]=useState(3),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[generation,setGeneration]=useState<string|null>(null);
 const account=connection.account,latest=latestInsights(data.posts),patterns=winningPatterns(drafts,data.posts,categories,Date.parse(now));
 const filtered=drafts.filter(d=>(!category||d.category_id===category)&&(!accountFilter||d.threads_account_id===accountFilter));
 const top=rankedPosts(filtered,data.posts,period,sort,Date.parse(now)),snapshots=top.flatMap(row=>row.insight?[row.insight]:[]);
 const measured=top.filter(row=>row.score!==null),totalScore=measured.length?measured.reduce((sum,row)=>sum+row.score!,0):null;
 const followerRows=data.accounts.filter(r=>!accountFilter||r.account_id===accountFilter).sort((a,b)=>Date.parse(b.fetched_at)-Date.parse(a.fetched_at)),followers=followerRows[0];
 const today=kstInput(now).slice(0,10),todayPosts=drafts.filter(d=>d.publication_status==="published"&&d.published_at&&kstInput(d.published_at).slice(0,10)===today);
 const todayMeasured=todayPosts.flatMap(d=>latest.has(d.id)?[latest.get(d.id)!]:[]).map(engagementScore).filter((n):n is number=>n!==null);
 const queued=drafts.filter(d=>d.scheduled_at&&d.publication_status!=="published"&&d.publish_stage!=="test_completed").sort((a,b)=>Date.parse(a.publish_next_retry_at??a.scheduled_at!)-Date.parse(b.publish_next_retry_at??b.scheduled_at!));
 const last=drafts.filter(d=>d.published_at).sort((a,b)=>Date.parse(b.published_at!)-Date.parse(a.published_at!))[0];
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError("");setNotice("");try{await action();}catch(e){setError(e instanceof Error?e.message:"처리하지 못했습니다.");}finally{setBusy(false);}}
 async function post(payload:unknown,path=base+"/performance"){const response=await fetch(path,{method:"POST",cache:"no-store",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),signal:AbortSignal.timeout(175000)});const result=await response.json();if(!response.ok)throw Error(result.error??"성과 작업을 완료하지 못했습니다.");return result;}
 const status=<>{error&&<p className="pro-feedback error" role="alert">{error}</p>}{notice&&<p className="pro-feedback success" role="status">{notice}</p>}</>;
 if(view==="dashboard")return <>
 <section className="pro-card p3-live-status"><div className="pro-card-title"><h2>LIVE STATUS</h2><span className={"pro-badge "+(account?.publishing_mode==="LIVE"?"danger":"warning")}>{account?.publishing_mode??"TEST"}</span></div>
 <div className="p3-status-grid"><div><span>계정</span><strong>{account?"@"+account.username:"Meta 계정 연결 필요"}</strong><small>{account?.connection_status??"Disconnected"}</small></div><div><span>게시 대기</span><strong>{queued.length}개</strong><small>{queued.filter(d=>d.publish_needs_attention).length}개 Needs Attention</small></div><div><span>다음 게시</span><strong>{date(queued.find(d=>!d.publish_needs_attention)?.scheduled_at)}</strong></div><div><span>최근 게시</span><strong>{date(last?.published_at)}</strong></div><div><span>API 상태</span><strong>{account?.api_message??(account?.last_checked_at?"마지막 확인 정상":"연결 대기")}</strong><small>{date(account?.last_checked_at)}</small></div><div><span>오늘 게시의 반응 점수</span><strong>{value(todayMeasured.length?todayMeasured.reduce((a,b)=>a+b,0):null)}</strong><small>{todayMeasured.length}/{todayPosts.length}개 글 수집 · 누적 반응</small></div></div>
 <p className="pro-help">{account?.publishing_mode==="LIVE"?"LIVE: 예약 큐가 실제 Threads에 게시됩니다.":"TEST: 실제 게시 요청 직전에 멈춥니다. 운영 준비 후 Accounts에서 LIVE로 전환하세요."}</p></section>
 <section className="pro-card"><div className="pro-card-title"><h2>이번 주 성과 · Top Post</h2><Link href="/analytics">성과 보기 →</Link></div><p>최근 7일 게시 {top.length}개 · Engagement Score {value(totalScore)} · {measured.length}개 글 측정</p>{top.find(r=>r.score!==null)?<p>{top.find(r=>r.score!==null)!.draft.body.slice(0,160)}<br/><strong>Score {value(top.find(r=>r.score!==null)!.score)}</strong></p>:<p className="pro-help">Top Post를 선정할 실제 반응 데이터 수집 중</p>}</section>
 <section className="pro-card"><div className="pro-card-title"><h2>데이터로 다음 이야기 준비하기</h2><Link href="/planner">다음 주 계획 →</Link></div>{patterns.enough&&patterns.categories.length?<p>최근 24시간 성과 표본에서 <strong>{patterns.categories[0].label}</strong>의 평균 반응 점수가 높았습니다. {patterns.categories[0].count}개 표본을 참고해 다음 주 계획을 만들어 보세요.</p>:<p className="pro-help">데이터가 더 필요합니다. 실제 게시와 Insights 수집이 쌓이면 다음 콘텐츠에 활용할 패턴을 보여드립니다.</p>}<small>최근 30일 · 24시간 snapshot {patterns.sample}/{10}개 · 인과관계가 아닌 관찰 결과</small></section></>;
 const heat=data.posts.filter(s=>s.after_hours===24&&engagementScore(s)!==null).flatMap(s=>{const d=top.find(t=>t.draft.id===s.draft_id)?.draft;if(!d?.published_at)return [];const local=kstInput(d.published_at);return [{day:new Date(local.slice(0,10)+"T00:00:00Z").getUTCDay(),hour:Number(local.slice(11,13)),score:engagementScore(s)!}];});
 const categoryResults=[...new Set(top.map(t=>t.draft.category_id))].map(id=>{const group=top.filter(t=>t.draft.category_id===id&&t.score!==null);return {label:categories.find(c=>c.id===id)?.name??"미분류",count:group.length,score:group.length?group.reduce((a,b)=>a+b.score!,0)/group.length:null};});
 const best=top.find(t=>t.draft.id===selected);
 const cut=period==="all"?null:Date.parse(now)-({"24h":1,"7d":7,"30d":30}[period]*86400000);
 const baseline=cut===null?[]:filtered.filter(d=>d.publication_status==="published"&&d.published_at&&Date.parse(d.published_at)<cut&&Date.parse(d.published_at)>=cut-(Date.parse(now)-cut));
 const baselineFollowers=period==="all"?null:followerRows.find(r=>Date.parse(r.fetched_at)<=cut!);
 return <>{status}<section className="pro-card"><div className="pro-card-title"><div><span className="pro-eyebrow">THREADS INSIGHTS</span><h2>실제 반응에서 다음 콘텐츠까지</h2></div><button className="pro-button ghost" disabled={busy||!connection.configured} onClick={()=>run(async()=>{const result=await post({});const response=await fetch(base+"/performance",{cache:"no-store",credentials:"same-origin"});if(!response.ok)throw Error("수집한 데이터를 불러오지 못했습니다.");onChange(await response.json());setNotice(result.collected?result.collected+"개 snapshot을 수집했습니다.":"수집할 checkpoint를 기다립니다. 이미 수집된 값은 반복 호출하지 않습니다.");})}>지금 수집</button></div>
 <div className="ops-toolbar"><label>기간<select value={period} onChange={e=>setPeriod(e.target.value as typeof period)}><option value="24h">24시간</option><option value="7d">7일</option><option value="30d">30일</option><option value="all">전체</option></select></label><label>카테고리<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">전체</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>계정<select value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="">전체</option>{account&&<option value={account.id}>@{account.username}</option>}</select></label><label>Top Posts 정렬<select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="engagement">Engagement</option><option value="replies">Replies</option><option value="reposts">Reposts</option><option value="views">Views</option></select></label></div>
 <p className="pro-help">선택 기간에 게시한 글의 최신 누적 반응입니다. 지표가 없는 글은 Unavailable로 표시합니다. 계정 Views는 별도 API 집계이며 게시물 Views와 분리 표시합니다. 최근 {data.posts.length}개 snapshot을 조회했습니다.{data.truncated?" 오래된 데이터 일부는 이 화면의 조회 범위 밖입니다.":""}</p></section>
 <div className="p3-metric-grid"><article className="pro-stat"><span>게시물</span><strong>{top.length}</strong><small>{cut===null?"전체 조회 범위":"직전 같은 기간 대비 "+(top.length-baseline.length>=0?"+":"")+(top.length-baseline.length)}</small></article>{POST_METRICS.map(metric=>{const total=metricTotal(snapshots,metric);return <article className="pro-stat" key={metric}><span>{metricLabels[metric]}</span><strong className={total.value===null?"p3-unavailable":""}>{value(total.value)}</strong><small>{total.coverage}/{top.length}개 글 측정</small></article>;})}<article className="pro-stat"><span>Followers · 최근 수집</span><strong className={!followers||followers.followers_count===null?"p3-unavailable":""}>{value(followers?.followers_count)}</strong><small>{followers?.followers_count!==null&&followers?.followers_count!==undefined&&baselineFollowers?.followers_count!==null&&baselineFollowers?.followers_count!==undefined?"기간 변화 "+(followers.followers_count-baselineFollowers.followers_count):"기간 변화 Unavailable"}</small></article><article className="pro-stat"><span>Engagement Score</span><strong className={totalScore===null?"p3-unavailable":""}>{value(totalScore)}</strong><small>{measured.length}/{top.length}개 측정 · Threads Pro 내부 점수</small></article></div>
 <section className="pro-card"><h2>계정 Daily Snapshot</h2>{followers?<><p className="pro-help">{followers.date} 요청 기간 · {date(followers.fetched_at)} 수집. Followers는 수집 시점의 총 팔로워입니다.</p><div className="p3-snapshot-row">{["views","likes","replies","reposts","quotes","followers_count"].map(m=><span key={m}>{m}: <strong>{value(followers[m as keyof typeof followers] as number|null)}</strong></span>)}</div></>:<p className="pro-help">계정 Insights 데이터 수집 중. 가짜 조회수나 팔로워를 표시하지 않습니다.</p>}</section>
 <section className="pro-card"><div className="pro-card-title"><h2>Top Posts</h2><span>{period} · {sort}</span></div><p className="pro-help">점수는 좋아요×1 + 답글×3 + 재게시×4 + 인용×4입니다. Meta의 공식 점수가 아닙니다. 조회 대비 반응률은 네 반응 지표가 모두 수집되고 Views가 0보다 클 때만 계산합니다.</p>
 {top.slice(0,20).map(row=><article className="p3-top-post" key={row.draft.id}><div className="pro-history-top"><span>{categories.find(c=>c.id===row.draft.category_id)?.name??"미분류"} · {date(row.draft.published_at)}</span><strong>Score {value(row.score)} · 반응률 {row.rate===null?"Unavailable":value(row.rate)+"%"}</strong></div><p>{row.draft.body}</p><div className="p3-snapshot-row">{POST_METRICS.map(m=><span key={m}>{metricLabels[m]} <strong>{value(row.insight?.[m])}</strong></span>)}</div><small>Threads ID {row.draft.threads_post_id} · {row.insight?"+"+row.insight.after_hours+"h snapshot · "+date(row.insight.fetched_at):"데이터 수집 중"}</small><div className="pro-row-actions"><button className="accent" disabled={busy||row.score===null} onClick={()=>{setSelected(row.draft.id);setGeneration(null);}}>이 스타일로 새 글 만들기</button><Link href="/history">게시 내역</Link></div></article>)}
 {!top.length&&<p className="pro-help">실제 게시 후 Insights가 쌓이면 Top Posts를 확인할 수 있습니다.</p>}</section>
 {best&&<section className="pro-card p3-followup"><div className="pro-card-title"><h2>성과 기반 후속 콘텐츠</h2><button disabled={busy} onClick={()=>setSelected(null)}>닫기</button></div><dl className="p3-style-facts"><div><dt>첫 문장</dt><dd>{best.draft.body.split(/[\n.!?]/)[0]}</dd></div><div><dt>길이 / 구조</dt><dd>{Array.from(best.draft.body).length}자 · {best.draft.body.split(/\n\s*\n/).length}개 문단</dd></div><div><dt>마무리 / 질문</dt><dd>{best.draft.body.split("\n").filter(Boolean).at(-1)} · {best.draft.body.includes("?")?"질문 포함":"질문 없음"}</dd></div><div><dt>카테고리 / 주제</dt><dd>{categories.find(c=>c.id===best.draft.category_id)?.name??"미분류"} / {best.draft.topic}</dd></div><div><dt>관측 반응</dt><dd>Score {value(best.score)} · Replies {value(best.insight?.replies)} · Reposts {value(best.insight?.reposts)}</dd></div></dl><p className="pro-help">AI가 원문의 후킹·말투·CTA·구조와 실제 반응을 분석해 다른 관점, 후속 정보, 질문, Part 2를 만듭니다. 원문을 문장만 바꿔 복제하지 않습니다.</p><label>후속 글 수<select value={followCount} onChange={e=>setFollowCount(Number(e.target.value))}><option value={3}>3개</option><option value={5}>5개</option><option value={10}>10개</option></select></label><div className="pro-row-actions"><button className="pro-button primary" disabled={busy} onClick={()=>run(async()=>{const result=await post({draftId:best.draft.id,count:followCount,requestId:crypto.randomUUID()},base+"/performance/followups");setGeneration(result.job.id);setNotice("후속 글을 DB에 저장했습니다. AI Composer에서 편집하고 예약하세요.");})}>{busy?"후속 글 생성 중…":"후속 글 생성"}</button>{generation&&<Link className="pro-button primary" href={"/composer?tab=ai&generation="+generation}>AI Composer에서 선택·예약 →</Link>}</div></section>}
 <div className="ops-chart-grid"><section className="pro-card"><h2>카테고리별 평균 반응 점수</h2><div className="ops-bars">{categoryResults.map(row=><div key={row.label}><span>{row.label} ({row.count})</span><div><i style={{width:row.score===null?0:row.score/Math.max(1,...categoryResults.map(r=>r.score??0))*100+"%"}}/></div><b>{value(row.score)}</b></div>)}</div><p className="pro-help">최신 누적 반응 · 표시 기간의 측정된 글만 집계</p></section>
 <section className="pro-card"><h2>요일 × 시간 성과 (KST)</h2><div className="p3-heat-scroll"><div className="p3-heatmap"><span/>{Array.from({length:24},(_,h)=><small key={h}>{h}</small>)}{["일","월","화","수","목","금","토"].map((day,index)=><div className="p3-heat-row" key={day}><small>{day}</small>{Array.from({length:24},(_,hour)=>{const group=heat.filter(r=>r.day===index&&r.hour===hour),score=group.length?group.reduce((n,r)=>n+r.score,0)/group.length:null;return <span key={hour} title={day+" "+hour+":00 · "+group.length+"개 · "+value(score)} style={{opacity:score===null?.12:.3+Math.min(.7,score/Math.max(1,...heat.map(r=>r.score)))}}>{score===null?"·":Math.round(score)}</span>;})}</div>)}</div></div><p className="pro-help">24시간 snapshot 기준 · 빈 칸은 수집 없음</p></section></div>
 <section className="pro-card"><h2>Winning Patterns & 추천 시간</h2><p className="pro-help">최근 30일의 비교 가능한 24시간 snapshot {patterns.sample}개. 전체 10개와 그룹별 3개 이상에서만 관찰 결과를 제공합니다.</p>{patterns.enough?<div className="p3-pattern-grid">{[["카테고리",patterns.categories],["길이",patterns.lengths],["게시 시간",patterns.times],["답글 스타일",patterns.replyStyles]].map(([label,rows])=><div key={label as string}><h3>{label as string}</h3>{(rows as typeof patterns.categories).slice(0,3).map(r=><p key={r.label}>{r.label} · {r.count}개 / 평균 {value(r.score)}</p>)}{!(rows as typeof patterns.categories).length&&<p>그룹별 데이터가 더 필요합니다.</p>}</div>)}<div><h3>반응 받은 주제</h3>{patterns.topics.map((r,index)=><p key={r.topic+index}>{r.topic} · {value(r.score)}</p>)}</div></div>:<p>데이터가 더 필요합니다.</p>}
 <h3>계정별 추천 시간</h3>{account?<>{patterns.byAccount.find(r=>r.accountId===account.id)?.times.length?patterns.byAccount.find(r=>r.accountId===account.id)!.times.map(r=><p key={r.label}>@{account.username} · {r.label} · {r.count}개 표본 / 평균 {value(r.score)}</p>):<p className="pro-help">@{account.username} · 데이터 수집 중</p>}</>:<p className="pro-help">Meta 계정 연결 후 실제 게시 데이터를 수집합니다.</p>}<Link href="/planner">최근 성과를 다음 주 계획에 반영 →</Link></section></>;
}
