"use client";
import {useState} from "react";
import type {ThreadsConnection} from "@/lib/threads-publishing";
const labels={connected:"Connected · Threads 연결 정상",expiring:"Token Expiring · 토큰 갱신 필요",token_error:"Token Error · Reconnect Required",disconnected:"Disconnected · Meta 계정 연결 필요",permission_required:"Permission Required · 게시 권한 추가 필요"};
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"}):"아직 없음";
export function ThreadsAccounts({connection,workspaceId,owner,onChange,outcome}:{connection:ThreadsConnection;workspaceId:string;owner:boolean;onChange:(value:ThreadsConnection)=>void;outcome?:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(outcome==="failed"?"Threads 연결을 완료하지 못했습니다. Meta 앱의 Callback URL, 테스터 승인과 요청 권한을 확인한 뒤 다시 연결해 주세요.":outcome==="permission_required"?"계정 확인은 완료됐지만 게시 권한이 부족합니다. 다시 연결해 기본 정보와 게시 권한을 모두 허용해 주세요.":""),[notice,setNotice]=useState(outcome==="connected"?"Threads 계정을 연결했습니다. 실제 게시 1건은 LIVE로 전환한 뒤 Composer에서 실행하세요.":outcome==="cancelled"?"Threads 연결을 취소했습니다.":""),[live,setLive]=useState("");
 const account=connection.account,status=account?.connection_status??"disconnected",base="/api/workspaces/"+workspaceId+"/threads";
 async function request(path:string,method:string,body:unknown){const response=await fetch(path,{method,credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(60000)});const result=await response.json();if(!response.ok)throw Error(result.error??"연결 작업을 완료하지 못했습니다.");return result;}
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError("");setNotice("");try{await action();}catch(e){setError(e instanceof Error?e.message:"연결 실패");}finally{setBusy(false);}}
 async function reload(){const result=await fetch(base,{cache:"no-store",credentials:"same-origin"}).then(r=>r.json());if(!result.error)onChange(result);}
 return <>
 <section className="pro-card pro-account-card"><div className="pro-account-card-header"><span className="pro-account-avatar large">@</span><div><h2>{account?"@"+account.username:"Threads 계정을 연결하세요"}</h2><p>{labels[status]}</p></div><span className={"pro-badge "+(account?.publishing_mode==="LIVE"?"danger":"warning")}>{account?.publishing_mode??"TEST"}</span></div>
 <div className="pro-account-details">{account&&<div><span>Threads 사용자 ID</span><strong>…{account.threads_user_id.slice(-6)}</strong></div>}<div><span>연결 시각</span><strong>{date(account?.connected_at)}</strong></div><div><span>토큰 만료</span><strong>{date(account?.token_expires_at)}</strong></div><div><span>마지막 갱신</span><strong>{date(account?.token_refreshed_at)}</strong></div><div><span>정상 API 확인</span><strong>{date(account?.last_checked_at)}</strong></div></div>
 <div className="p3-permissions">{["threads_basic","threads_content_publish"].map(p=><span key={p} className={"pro-badge "+(account?.granted_permissions.includes(p)?"success":"warning")}>{p} · {account?.granted_permissions.includes(p)?"허용":"필요"}</span>)}<span className={"pro-badge "+(account?.granted_permissions.includes("threads_manage_insights")?"success":"neutral")}>threads_manage_insights · {account?.granted_permissions.includes("threads_manage_insights")?"허용":"선택 · 게시에 불필요"}</span></div>
 {account?.api_message&&<p className="pro-feedback error">{account.api_message}{account.api_error_code?" · "+account.api_error_code:""}</p>}
 {error&&<p className="pro-feedback error" role="alert">{error}</p>}{notice&&<p className="pro-feedback success" role="status">{notice}</p>}
 <div className="pro-row-actions"><button className="pro-button primary" disabled={busy||!owner||!connection.oauthConfigured} onClick={()=>run(async()=>{const result=await request("/api/threads/oauth/start","POST",{workspaceId});window.location.assign(result.url);})}>{account?"Threads 다시 연결":"Threads 계정 연결"}</button>
 {account&&<><button className="pro-button ghost" disabled={busy||!owner||status==="disconnected"} onClick={()=>run(async()=>{try{onChange(await request(base,"POST",{}));setNotice("계정·권한·토큰 상태를 확인했습니다.");}catch(e){await reload();throw e;}})}>연결 상태 확인</button><button disabled={busy||!owner||status==="disconnected"} onClick={()=>run(async()=>{onChange(await request(base,"PATCH",{action:"disconnect"}));setNotice("연결을 해제했습니다. 글과 게시 이력은 보존됩니다.");})}>연결 해제</button></>}
 </div>{!owner&&<p className="pro-help">계정 연결과 LIVE 전환은 workspace owner가 관리합니다.</p>}</section>
 <section className="pro-card"><h2>TEST에서 준비하고 LIVE로 운영하세요</h2><p className="pro-help">새 연결은 항상 TEST입니다. TEST는 컨테이너 준비 후 멈추며 실제 Threads 게시물과 Published 수치를 만들지 않습니다. LIVE에서는 즉시 게시와 예약 큐가 실제 게시됩니다.</p>
 {owner&&account&&status!=="disconnected"&&<div className="p3-mode-controls">{account.publishing_mode==="LIVE"?<button className="pro-button ghost" disabled={busy} onClick={()=>run(async()=>{onChange(await request(base,"PATCH",{action:"mode",mode:"TEST"}));setNotice("TEST로 전환했습니다.");})}>TEST로 전환</button>:<><label>실제 게시를 시작하려면 LIVE 입력<input value={live} onChange={e=>setLive(e.target.value)} placeholder="LIVE" autoComplete="off"/></label><button className="pro-button primary" disabled={busy||live!=="LIVE"||!["connected","expiring"].includes(status)} onClick={()=>run(async()=>{onChange(await request(base,"PATCH",{action:"mode",mode:"LIVE",confirmation:live}));setLive("");setNotice("LIVE 운영을 시작했습니다. 대기 중인 예약 글은 지정 시간부터 게시됩니다.");})}>LIVE 게시 활성화</button></>}</div>}
 </section>
 {!connection.oauthConfigured&&<section className="pro-card pro-setup"><h2>Meta 앱 연결 준비</h2><p>Meta 개발자 Dashboard에서 Threads API 앱을 준비한 뒤 아래 서버 설정을 추가하면 이 화면의 연결 버튼이 활성화됩니다.</p><ul><li><code>THREADS_APP_ID</code> — Threads App ID</li><li><code>THREADS_APP_SECRET</code> — Threads App Secret</li><li><code>THREADS_REDIRECT_URI</code> — <code>https://threads-duo-os.vercel.app/api/threads/oauth/callback</code></li></ul><p>Meta 앱의 Redirect Callback URL도 위 주소와 정확히 같아야 합니다. 개발 모드에서는 Threads 테스터 초대를 수락한 계정으로 연결하세요. 일반 사용자 연결에는 해당 권한의 App Review가 필요합니다.</p><a href="https://developers.facebook.com/apps/" target="_blank" rel="noreferrer">Meta 개발자 Dashboard ↗</a><p className="pro-help">App Secret과 사용자 토큰은 사이트 입력란이나 채팅에 넣지 않습니다. 작성·AI 생성·예약 준비는 계속 사용할 수 있습니다.</p></section>}
 </>;
}
